# port: /dev/ttyDXL_follower_arm
port: /dev/ttyDXL

groups:
  arm:
    operating_mode: position
    profile_type: velocity
    profile_velocity: 0
    profile_acceleration: 0
    torque_enable: true

singles:
  gripper:
    operating_mode: current_based_position
    profile_type: velocity
    profile_velocity: 0
    profile_acceleration: 0
    torque_enable: true
